# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aa7e7b41a856ccfc222e236d92ed0a0215cfaef16b1a689017d3fcf569aa52d07396095b7874a4db14d49002aaa936d32150277f1c46428e2694e6a4b3d2ac3

test:
  secret_key_base: 8d20d42a13f4ab1f1461bebfc708365bb881208a829d98e1428c87f47a6a777e3092cf2d22c92ee797ccf75668d38058d6b17588141153bcca8aabb1626c953c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
