# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 558a719ebc497c4703af018df6897cba7feac9df67208a645603f63e6447290ab4035338a7ff04c3389a9c9ee1cb83baae2636d503e4900838d81b59ca41c726

test:
  secret_key_base: f96d4c86d12da031a3109e9316de08317ed80851e6fa89ddd14c5290899424caeda8dad2bdb13230299b2b4f1307ca2d2e58e978e8d575219a5f697c1e6537c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
