# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9e8c5c687ae81fee27ec9188740133e1ca426e631d3712ea850a8d967399977a4bdb042736eaf49d13f87bd024799c50238ce560237a2930b390bc2edd65656

test:
  secret_key_base: f5491635ddb42e456fa99f3d6101211ec1735e95fc47f30aa075ba3f73bdd57c63e682ef39999c3b3b5bf4c416e771449de2961c6037c17e93a60fd980f0f43a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
